FORMAT: 1A
HOST: https://flame-dev.1n1.hk

# Fenix

A web API for Fenix project.

## Common Attributes 

+ `bbt_id`溫度計ID

    toUpper(sha1(toUpper(XX:XX:XX:XX:XX:XX_1N1_BBT)))

    PlainText:
    
        XX:XX:XX:XX:XX:XX_1N1_BBT
    Hash:
    
        56CDB9A741552F7EECB3FC215814A8B617B99E5D

+ `phone_id` 手機ID

    toUpper(sha1(toUpper(XX:XX:XX:XX:XX:XX_1N1_PHONE)))
    
    PlainText:
    
        XX:XX:XX:XX:XX:XX_1N1_PHONE
    Hash:
    
        3879F289A08E2B62E4AF452183C600F0B91A1CAC

+ `product_code` 產品代碼

    隨產品附的`product_code`，algorithm=`toUpper(sha1(haoyunlai_SN))`
    
    PlainText:
    
        haoyunlai_1
    Hash:
    
        AFC4E7CCABD9583DCA2F563DB1A9419A39E817D0


# Group Service

## Service Status [/v1/status]

### Get Service Status [GET]

+ Response 200 (application/json)

    + Body
    
            {
              "status": "ok",
              "result": {
                "version": "v1",
                "mode": "release"
              }
            }


# Group Product Code

## Product Status [/v1/products/{product_code}]

檢查啟動碼是否啟用過。

+ Parameters
    + product_code:debug-code (string,required) 

### Get Product Code Status [GET]

+ Response 200 (application/json)

    + Body 
    
            {
              "status": "ok",
              "result": {
                "type": "full",
                "code": "debug-code",
                "issued_at": "2015-08-10T08:45:00Z",
                "activated_at": "2015-08-11T07:29:59Z",
                "activated_by": "5FE1EEA69376B035F998F6CA001CA74A4D3404B0"
              }
            }


## Create Product Code [/v1/products]

Create a code. **Only avaliable in Debug**

### Post A Code [POST]

+ Request 

    + Body 
        
            {"code":"debug-code3","type":"full"}
            
            
+ Response 200 (application/json)

    + Body 
    
            {
                 "status": "ok"
            }
            
## Reset Product Code [/v1/products/{product_code}/reset]

Reset a Code,if anyone use this code, it will be removed. **Only avaliable in Debug**

+ Parameters
    + product_code:debug-code (string,required) 


### Reset Code [GET]

+ Response 200 (application/json)
    
    + Body
    
            {
              "status": "ok"
            }


# Group Member

## Register [/v1/members]

註冊會員資料。

### Register [POST]


+ Request Register (application/json)

    + Body 
        
            {
                "bbt_id":"bbt_id",
                "email":"email",
                "password":"password",
                "phone_id":"phone_id",
                "product_code":"debug-code",
                "type":"basic"
            }

    

+ Response 200 (application/json)

    + Body 
    
            {
              "status": "ok",
              "result": {
                "user": {
                  "member_id": "5FE1EEA69376B035F998F6CA001CA74A4D3404B0",
                  "secret": "3CCF24FF8990E0B098B3B1A32E586D40A8EB550B",
                  "phone_id": "phone_id",
                  "product_code": "debug-code",
                  "bbt_id": "bbt_id",
                  "is_allow_migrate": true,
                  "first_name": null,
                  "last_name": null,
                  "birthday": null,
                  "registered_at": "2015-08-11T07:29:59Z",
                  "modified_at": "2015-08-11T07:29:59Z",
                  "synced_at": "2015-08-11T07:29:59Z"
                },
                "setting": {
                  "member_id": "5FE1EEA69376B035F998F6CA001CA74A4D3404B0",
                  "is_backlight": true,
                  "alarm_sound_vol": 0,
                  "alarm_at": "15:29:59",
                  "sync_sound_vol": 1,
                  "modified_at": "2015-08-11T07:29:59Z"
                }
            }


## Login [/v1/login]

註冊會員資料。

### Login [POST]


+ Request Login (application/json)
    
    + Body
    
            {"email":"email","password":"password"}


+ Response 200 (application/json)
    
    + Body 
    
            {
              "status": "ok",
              "result": {
                "user": {
                  "member_id": "5FE1EEA69376B035F998F6CA001CA74A4D3404B0",
                  "secret": "3CCF24FF8990E0B098B3B1A32E586D40A8EB550B",
                  "phone_id": "phone_id",
                  "product_code": "debug-code",
                  "bbt_id": "bbt_id",
                  "is_allow_migrate": true,
                  "first_name": null,
                  "last_name": null,
                  "birthday": null,
                  "registered_at": "2015-08-11T07:29:59Z",
                  "modified_at": "2015-08-11T07:29:59Z",
                  "synced_at": "2015-08-11T07:29:59Z"
                },
                "setting": {
                  "member_id": "5FE1EEA69376B035F998F6CA001CA74A4D3404B0",
                  "is_backlight": true,
                  "alarm_sound_vol": 0,
                  "alarm_at": "15:29:59",
                  "sync_sound_vol": 1,
                  "modified_at": "2015-08-11T07:29:59Z"
                }
              }
            }
